RE-1490 Fix failing snapshot script
Snapshots are currently failing due to a recent change in
scripts/create_cloud_image.py:

```
>>> from six import xrange
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name xrange
>>> from six.moves import xrange
>>>
```

This commit updates the six import.