RE-2310 Fix release modifier regex matches
matcher.matches() will only return true if the pattern matches the whole
input string. The patterns in use do not cover the whole input string
only the trigger part and surrounding whitespace. That means that
using the current code .matches() won't trigger.

In a previous commit I removed .matches() and it caused release
jobs to fail because Jenkins CPS groovy does not cooerce matcher
objects to Boolean when matching method signatures, but vanilla
groovy does.

Consider the following snippet:
====================
def func(Boolean f){
  print f
}

Boolean match(){
    return ("foo" =~ /oo/)
}
func(match())
====================
This snippet returns true in groovy and:
java.lang.NoSuchMethodError: No such DSL method 'func'

in Pipeline/CPS groovy, because theres no method func(Matcher f).

This commit removes the .matches() call, but changes the operator to ==~
which requires an exact match, and always returns a Boolean.
To accomodate this, the patterns have been expanded to allow any
text before and after the required pattern.

Test code:
====================
def func (Boolean f){
    print f
}

m = "before foo  after" ==~ /.*oo.*/
assert m instanceof Boolean
func(m)
====================

This outputs "true" in both groovy and cps groovy.