Add github property for rpc-openstack
Triggering is currently failing with the following:

Mar 23, 2017 5:41:28 PM org.jenkinsci.plugins.ghprb.GhprbRootAction getTriggers
SEVERE: Failed to match signature for trigger on project: RPC-AIO_master-xenial-pr
java.lang.IllegalStateException: A GitHub project url is required.
...

This is a futile attempt at fixing.